plugin: gcp_compute
projects:
  - infra-666666
auth_kind: serviceaccount
service_account_file: ~/Downloads/infra-666666-123123aaa123.json
filters:
hostnames:
  - name
groups:
  app: "'reddit-app' in name"
  db: "'reddit-db' in name"
compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
  reddit_int_ip: networkInterfaces[0].networkIP
